services:
  zmc:  # ZeroMQ Publisher
    build: ./zmc
    container_name: zmc
    networks:
      - zmq-net

  zmq-serial:  # ZeroMQ Subscriber + Serial Sender
    build: ./zmq-serial
    container_name: zmq-serial
    privileged: true
    devices:
      - "/dev/ttyUSB0:/dev/ttyUSB0"  # Map USB Serial Port
    environment:
      - ZMC_HOST=tcp://zmc:5555  # ZMQ Publisher address
    networks:
      - zmq-net
    depends_on:
      - zmc  # Ensure ZMC is running first

networks:
  zmq-net:
    driver: bridge
